save

diff --git a/mothvc b/mothvc
--- a/mothvc
+++ b/mothvc
@@ -24,9 +24,15 @@ set -e
 set -u
 
 
+# Configuration
 vc_dir=.git
 global_config="$HOME/$vc_dir"config
 head_path="$vc_dir"/HEAD
+hash_prgm=sha1sum
+
+# Command substitution is used to remove the trailing \n
+hash_text_len=$(h=$(printf '' | "$hash_prgm" | cut -d ' ' -f 1); \
+    printf '%s' "$h" | wc -c)
 
 
 hash_to_path() {
@@ -43,8 +49,23 @@ hash_to_path() {
     hash="$1"
     ############
     hash_start=$(printf %s "$1" | cut -c 1-2)
-    hash_end=$(printf %s "$1" | cut -c 3-40)
+    hash_end=$(printf %s "$1" | cut -c 3-"$hash_text_len")
     printf %s "$vc_dir/objects/$hash_start/$hash_end"
+}
+
+
+get_hash() {
+    local fn
+    ############
+    if [ "$#" -ne 1 ]
+    then
+        printf '%s: get_hash fn\n' "$0" 1>&2
+        return 1
+    fi
+    fn="$1"
+    ############
+
+    "$hash_prgm" "$fn" | cut -d ' ' -f 1
 }
 
 
@@ -69,11 +90,11 @@ hash_file() {
     mode="$3"
     ############
 
-    tmp_obj="$(mktemp)"
+    tmp_obj=$(mktemp)
     size=$(stat -c %s "$path")
     printf '%s %s\0' "$type" "$size" > "$tmp_obj"
     cat "$path" >> "$tmp_obj"
-    hash=$(sha1sum "$tmp_obj" | cut -d ' ' -f 1)
+    hash=$(get_hash "$tmp_obj")
 
     if [ "$mode" = store ]
     then
@@ -218,7 +239,7 @@ walk_tree() {
 
     tree_path=$(hash_to_path "$tree_hash")
 
-    tmp="$(mktemp)"
+    tmp=$(mktemp)
     openssl zlib -d -in "$tree_path" | tree_to_text > "$tmp"
 
     exec 3< "$tmp"
@@ -292,10 +313,10 @@ walk_dir() {
     dir="$1"
     ############
 
-    tmp="$(mktemp)"
-    tmp_tree="$(mktemp)"
-    tmp_tree_sorted="$(mktemp)"
-    tmp_tree_binary="$(mktemp)"
+    tmp=$(mktemp)
+    tmp_tree=$(mktemp)
+    tmp_tree_sorted=$(mktemp)
+    tmp_tree_binary=$(mktemp)
 
     find "$dir" -mindepth 1 -maxdepth 1 ! -path '*/'"$vc_dir" \
         -exec basename '{}' \; | sed -E 's_^\./__' > "$tmp"
@@ -389,14 +410,23 @@ commit() {
     other_parent_hash="$2"
     ############
 
-    tmp_commit_file="$(mktemp)"
+    tmp_commit_file=$(mktemp)
 
-    tree_hash=$(walk_dir "$(pwd)")
+    if find . -type f ! -path '*/.git/*' \( -path '*:*' -o -path '*
+*' \)
+    then
+        printf '%s: ERROR: File path contains a semicolon or newline char\n' \
+            "$0" 1>&2
+        return 1
+    fi
 
-    author="$(get_name)"
-    email="$(get_email)"
-    parent="$(get_current_checkout)"
-    time="$(date +%s)"
+    tree_hash=$(walk_dir "$wd")
+
+    author=$(get_name)
+    email=$(get_email)
+    parent=$(get_current_checkout)
+    time=$(date +%s)
+    time_zone=$(date +%z)
 
     printf 'tree %s\n' "$tree_hash" > "$tmp_commit_file"
 
@@ -410,11 +440,13 @@ commit() {
         printf 'parent %s\n' "$other_parent_hash" >> "$tmp_commit_file"
     fi
 
-    {
-    printf 'author %s <%s> %s +1030\n' "$author" "$email" "$time"
-    printf 'committer %s <%s> %s +1030\n\n' "$author" "$email" "$time"
-    printf '%s\n' "$message"
-    } >> "$tmp_commit_file"
+    for role in author committer
+    do
+        printf '%s %s <%s> %s %s\n' "$role" "$author" "$email" "$time" \
+            "$time_zone" >> "$tmp_commit_file"
+    done
+
+    printf '\n%s\n' "$message" >> "$tmp_commit_file"
 
     hash=$(hash_file "$tmp_commit_file" commit store)
 
@@ -434,12 +466,28 @@ commit() {
     rm "$tmp_commit_file"
 }
 
+
+
+
 usage='Usage:
     mothvc init
     mothvc checkout branch|hash
     mothvc commit message
     mothvc merge ours|theirs branch|commit
+    mothvc branch [new_branch]
 '
+
+wd=$(pwd)
+
+
+if [ ! -d "$vc_dir" ]
+then
+    printf '%s: ERROR: Not in the base directory of a mothvc repository\n' \
+        "$0" 1>&2
+
+    exit 1
+fi
+
 
 ############
 if [ "$#" -lt 1 ]
@@ -470,13 +518,13 @@ then
     target_hash=$(branch_to_commit "$branch_or_commit")
     target_tree_hash=$(commit_to_tree "$target_hash")
 
-    commit_hash="$(get_current_checkout)"
+    commit_hash=$(get_current_checkout)
     tree_hash=$(commit_to_tree "$commit_hash")
 
-    walk_tree "$(pwd)" "$tree_hash" check
-    walk_tree "$(pwd)" "$tree_hash" delete
+    walk_tree "$wd" "$tree_hash" check
+    walk_tree "$wd" "$tree_hash" delete
 
-    walk_tree "$(pwd)" "$target_tree_hash" copy
+    walk_tree "$wd" "$target_tree_hash" copy
 
     if [ "$branch_or_commit" = "$target_hash" ]
     then
@@ -511,26 +559,47 @@ then
     branch_or_commit="$3"
     ############
 
-    commit_hash="$(get_current_checkout)"
+    commit_hash=$(get_current_checkout)
     tree_hash=$(commit_to_tree "$commit_hash")
 
     # Check for modifications
-    walk_tree "$(pwd)" "$tree_hash" check
+    walk_tree "$wd" "$tree_hash" check
 
     other_parent_hash=$(branch_to_commit "$branch_or_commit")
     other_parent_tree_hash=$(commit_to_tree "$other_parent_hash")
 
     if [ "$merge_option" = theirs ]
     then
-        walk_tree "$(pwd)" "$other_parent_tree_hash" copy
+        walk_tree "$wd" "$other_parent_tree_hash" copy
     elif [ "$merge_option" = ours ]
     then
-        walk_tree "$(pwd)" "$other_parent_tree_hash" copy
-        walk_tree "$(pwd)" "$tree_hash" copy
+        walk_tree "$wd" "$other_parent_tree_hash" copy
+        walk_tree "$wd" "$tree_hash" copy
     else
         printf 'Invalid merge option\n' 1>&2
         exit 1
     fi
 
     commit Merge "$other_parent_hash"
+
+elif [ "$option" = branch ]
+then
+    ############
+    if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]
+    then
+        printf 'Usage: %s branch [new_branch]\n' "$0" 1>&2
+        exit 1
+    fi
+    if [ "$#" -eq 2 ]
+    then
+        new_branch="$2"
+    else
+        new_branch=''
+    fi
+    ############
+
+    if [ -z "$new_branch" ]
+    then
+        find "$vc_dir"/refs/heads/ -type f -exec basename '{}' \;
+    fi
 fi
